version: '3.7'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Mel
      - POSTGRES_USER=Mel
      - POSTGRES_DB=gemdealer
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=notSoSecretHere
      - DJANGO_DEBUG_MODE=0
      - POSTGRES_PASSWORD=Mel
      - POSTGRES_USER=Mel
      - POSTGRES_DB=gemdealer
    depends_on:
      - db
